theme: minima "minima: skin:sunrise"
title: Observations, Opinions & Opens 
author: wilma van wezenbeek
description:  #libraries #communities #knowledgeequity #openscience #openaccess #openeducation #connectingtheopens #myownopinion
