theme: jekyll-theme-cayman
title: Observations, Opinions & Opens 
author: wilma van wezenbeek
url: "https://github.com/wvanwezenbeek"
description: I like to write, listen, observe and then see opportunities or connections
