theme: jekyll-theme-tactile
title: Observations, Opinions & Opens 
author: wilma van wezenbeek
affiliation: https://github.com/wvanwezenbeek
description: I like to write, listen, observe and then see opportunities or connections
