theme: minima 
title: Observations, Opinions & Opens 
author: Wilma van Wezenbeek
description:  #libraries #openscience #openaccess #openeducation #connectingtheopens #communities #knowledgeequity #myownopinion
