theme: minima 
title: Observations, Opinions & Opens 
author: Wilma van Wezenbeek
description: About libraries, open science, open access, open education, connecting the opens, knowledge equity (all my own opinion) 
