theme: minima "minima: skin:sunrise"
title: Observations, Opinions & Opens 
author: wilma van wezenbeek
description:  About libraries, open science, open access,  open education, communities, knowledgeequity (all my own opinion)
